### PR TITLE
Update Main.php

### PR DESCRIPTION
**Pull request by LordJoshie**
woooh, I contributed so much. lol

### CODE REVIEW

**Comment by jojoe77777** [comment]
I need a quintuple face palm emoji right now. That has been like that since Nov 7, 2015.

Thanks.

**Comment by LordJoshie** [comment]
LOL. no problem. That was brought up by my co-owner, and this was my very
first PR.

May I ask.. how could I run a command as a player, and give them temp OP
perms to run it...

like with tap-to-do, you can do %op at the end of a command, and it will
run the command as the player, as if they had OP perms...even tho they
don't.

**Comment by jojoe77777** [comment]
I haven't ever tried it, but maybe this would work:

/slapper edit <id> addcommand op <player>
/slapper edit <id> addcommand rca <player> command_requiring_op
/slapper edit <id> addcommand deop <player>

Just make sure that the player is getting DEOP'd properly - not my fault if someone accidentally gets OP for more than a few MS.

**Comment by LordJoshie** [comment]
is there any updated 'how-to' type documentation I can review somewhere for more information on advanced functions of the plugin like this ?

**Comment by LordJoshie** [comment]
My dude.... using 'rca' runs commands as a player with OP perms.... 

For the next time you're asked, that's how. 

I assumed it just ran the command as the player with their level of permissions, not console level of perms. :P 

This makes things easier.

**Pull request merged**
