### PR TITLE
Added to Newest Protocol

### PR DESCRIPTION
**Pull request by CodsXBlastin**

### CODE REVIEW

**Comment by dktapps** [comment]
I shit you not, this is the 14th pull request that does this exact thing.

**Comment by supercrafter333** [comment]
I think that the author is not longer activ

**Comment by KurojakiKaoru** [comment]
The point is, there doesn't need to be 14 different pull requests changing the exact same thing. Won't make the change happen any faster.

**Comment by CodsXBlastin** [comment]
Alright No worries mate

> I shit you not, this is the 14th pull request that does this exact thing.

No worries mate

**Comment by CodsXBlastin** [comment]
Useless pull

**Pull request closed without merging**
