### PR TITLE
Fixes those errors.

### PR DESCRIPTION
**Pull request by ArceusMatt**
i tested this and it works. (ALPHA12)

### CODE REVIEW

**Comment by ArceusMatt** [comment]
Not sure why github wouldn't let me make changes to master branch instead of slapper-trait so... sorry if that's a problem. Annoying for me because i only made 1 commit on my fork.

**Comment by jojoe77777** [comment]
None of the commits are yours

**Comment by ArceusMatt** [comment]
I noticed because of slapper-trait branch, if you want my changes just check my commit on my fork.
Unless you didn't place the 2 simple voids for a reason?

**Comment by dktapps** [comment]
don't use development builds
don't use development builds
don't use development builds
don't use development builds
don't use development builds

**Pull request closed without merging**
