### PR TITLE
Slapper 1.3.0 - Proper 0.16 update

### PR DESCRIPTION
**Pull request by jojoe77777**
Needs a bit of testing, but so far it looks ready to merge.

### CODE REVIEW

**Comment by jojoe77777** [comment]
@legoboy0215 
@dktapps
@Sandertv
@Misteboss

**Comment by Misteboss** [comment]
@dktapps

**Comment by Misteboss** [comment]
Inventory contain doesn't work :| (ex : if you have a diamond sword, the Slapper doesn't have it, same for armor)

**Comment by Misteboss** [comment]
@jojoe77777

**Comment by Sandertv** [comment]
I noticed this is just a client bug. Relog or reload the chunk and it will be there.

**Comment by Misteboss** [comment]
Do you have twitter or something like that so we can talk privately ? @jojoe77777

**Pull request merged**
